### ISSUE TITLE
Création environnement - Création comptes - Compte github ou gitlab 

### ISSUE THREAD

**Issue by anjunjin** [anjunjin/PFE-ING3-IA#1]
done

**Comment by MRGotIdeas** [comment]
Tu peux décrire un peu plus la tâche que tu dois faire et une fois terminée ✅ tu peux fermer l'issue : close 📕 

Tu peux également rajouter des labels : créer un label "environnement" par exemple, un label "data", un label "model", etc.

Je te ferme cette issue là, et il faudra que tu fermes les issues que tu as terminé.
